-- MySQL Script generated by MySQL Workbench
-- 12/22/15 16:52:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema postwork
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema postwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `postwork` DEFAULT CHARACTER SET utf8 ;
USE `postwork` ;

-- -----------------------------------------------------
-- Table `postwork`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postwork`.`utilisateur` (
  `IdUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `Pseudo` VARCHAR(45) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `DateNaissance` DATE NOT NULL,
  `MotDePasse` VARCHAR(255) NOT NULL,
  `StatusMail` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 : désactivé\n1 : activé\n2 : bloqué',
  `StatusWeb` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 : désactivé\n1 : activé\n2 : bloqué',
  `Administrateur` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`IdUtilisateur`),
  UNIQUE INDEX `Pseudo_UNIQUE` (`Pseudo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postwork`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postwork`.`categorie` (
  `IdCategorie` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postwork`.`fqdn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postwork`.`fqdn` (
  `IdFQDN` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(255) NOT NULL,
  `IP` VARCHAR(255) NOT NULL DEFAULT '88.177.168.133',
  PRIMARY KEY (`IdFQDN`),
  UNIQUE INDEX `Nom_UNIQUE` (`Nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postwork`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postwork`.`site` (
  `IdSite` INT NOT NULL AUTO_INCREMENT,
  `Portfolio` TINYINT(1) NOT NULL COMMENT 'true : portfolio\nfalse : projet',
  `StatusVhost` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 : désactivé\n1 : activé\n2 : bloqué',
  `StatusBDD` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 : désactivé\n1 : activé\n2 : bloqué',
  `Description` VARCHAR(255) NULL,
  `IdUtilisateur` INT NOT NULL,
  `IdFQDN` INT NOT NULL,
  `IdCategorie` INT NULL,
  PRIMARY KEY (`IdSite`),
  INDEX `UtilisateurSite_idx` (`IdUtilisateur` ASC),
  INDEX `CategorieSite_idx` (`IdCategorie` ASC),
  INDEX `FQDNSite_idx` (`IdFQDN` ASC),
  CONSTRAINT `UtilisateurSite`
    FOREIGN KEY (`IdUtilisateur`)
    REFERENCES `postwork`.`utilisateur` (`IdUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CategorieSite`
    FOREIGN KEY (`IdCategorie`)
    REFERENCES `postwork`.`categorie` (`IdCategorie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FQDNSite`
    FOREIGN KEY (`IdFQDN`)
    REFERENCES `postwork`.`fqdn` (`IdFQDN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postwork`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postwork`.`tag` (
  `IdTag` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postwork`.`tagger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postwork`.`tagger` (
  `IdTag` INT NOT NULL,
  `IdSite` INT NOT NULL,
  PRIMARY KEY (`IdTag`, `IdSite`),
  INDEX `SiteTagger_idx` (`IdSite` ASC),
  CONSTRAINT `TagTagger`
    FOREIGN KEY (`IdTag`)
    REFERENCES `postwork`.`tag` (`IdTag`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SiteTagger`
    FOREIGN KEY (`IdSite`)
    REFERENCES `postwork`.`site` (`IdSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
